arch: amd64
cores: 3
hostname: hl-pbs-backup
memory: 2048
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=bc:24:11:33:26:ec,ip=dhcp,ip6=dhcp,type=veth
mp0: /mnt/backup-hdd,mp=/mnt/backup-hdd
features: fuse=1,nesting=1,mount=nfs
startup: delay=30 
ostype: debian
rootfs: local-lvm:vm-200-disk-0,size=25G
swap: 512
tags: hl-k8s
