apiVersion: apps/v1
kind: Deployment
metadata:
  name: beszel
  namespace: beszel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beszel
  template:
    metadata:
      labels:
        app: beszel
    spec:
      nodeSelector:
        tier: always-on
      containers:
        - name: beszel
          image: henrygd/beszel:0.18.7
          ports:
            - containerPort: 8090
          volumeMounts:
            - name: data
              mountPath: /beszel_data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: beszel-data