apiVersion: v1
kind: Service
metadata:
  name: beszel
  namespace: beszel
spec:
  type: NodePort
  selector:
    app: beszel
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30090