apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - beszel
  - miniflux
  - n8n
  - nut
  - hindsight
  - open-webui
  - monitoring
  - hermes-agent
  - hermes-family
  - karakeep
  - searxng
  - homepage
  - portfolio
